language: ruby
sudo: false
os:
  - osx

before_install:
  - gem install bundler
  - brew update
  - brew install qt5 sqlite3
  - bundle config build.qml --with-qmake=$(brew --prefix qt5)/bin/qmake

script:
  - rake spec

rvm:
  - 2.2.0

bundler_args: --jobs 1 --retry 3

notifications:
  email: false